language: python

matrix:
  include:
    - os: linux
      python:
        "3.7"
            
      install: 
        - python3 -m pip install pyservoce

      script:
        - cd pytest
        - python3 ./inctest.py
        - python3 ./apitest.py

    - os: linux
      python:
        "3.7"
            
      install: 
        - env | grep DISPLAY
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo add-apt-repository ppa:freecad-maintainers/occt-releases -y
        - sudo add-apt-repository ppa:freecad-maintainers/freecad-stable -y
        - sudo apt-get update
        - sudo apt install -y libocct-foundation-7.3 libocct-ocaf-7.3 libocct-data-exchange-7.3 libocct-foundation-dev libocct-ocaf-dev libocct-data-exchange-dev
        - sudo apt install python3-pybind11
        
        - python3 -m pip install licant
        - python3 ./setup.py install

      script:
        - cd pytest
        - python3 ./inctest.py
        - python3 ./apitest.py

    - os: linux
      python:
        "3.7"

      addons:
        apt:
          packages:
            - g++-6
            
      install: 
        - env | grep DISPLAY
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo add-apt-repository ppa:freecad-maintainers/occt-releases -y
        - sudo add-apt-repository ppa:freecad-maintainers/freecad-stable -y
        - sudo apt-get update
        - sudo apt install -y libocct-foundation-7.3 libocct-ocaf-7.3 libocct-data-exchange-7.3 libocct-foundation-dev libocct-ocaf-dev libocct-data-exchange-dev
 
        - git clone https://github.com/google/googletest googletest/
        - cd googletest
        - cmake .
        - make
        - sudo make install
        - cd ..

        - cd igris
        - cmake .
        - make
        - sudo make install
        - cd ..

        - cd nos
        - cmake .
        - make
        - sudo make install
        - cd ..

        - source ./tools/set_occt_paths.sh
        - cmake .
        - make

script:
  - echo "Ok"
