language: python

matrix:
  include:
    - name: "Ubuntu: Load from pypi"
      os: linux
      python:
        "3.8"
            
      install: 
        - python3 -m pip install pyservoce

      script:
        - cd pytest
        - python3 ./inctest.py
        - python3 ./apitest.py

     - name: "OSX: Load from pypi"
       os: osx
       osx_image: xcode11.2
       language: shell

       install:
         - python3 -m pip install pyservoce

       script:
         - cd pytest
         - python3 ./inctest.py
         - python3 ./apitest.py

    - name: "Ubuntu: Build by setup.py"
      os: linux
      python:
        "3.7"
            
      install: 
        - env | grep DISPLAY
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo add-apt-repository ppa:freecad-maintainers/occt-releases -y
        - sudo add-apt-repository ppa:freecad-maintainers/freecad-stable -y
        - sudo apt-get update
        - sudo apt install -y libocct-foundation-7.3 libocct-ocaf-7.3 libocct-data-exchange-7.3 libocct-foundation-dev libocct-ocaf-dev libocct-data-exchange-dev
        - sudo apt install python3-pybind11
        
        - python3 -m pip install licant
        - python3 ./setup.py install

      script:
        - cd pytest
        - python3 ./inctest.py
        - python3 ./apitest.py

    - name: "Ubuntu: Build by cmake"
      os: linux
      python:
        "3.7"

      install: 
        - env | grep DISPLAY
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo add-apt-repository ppa:freecad-maintainers/occt-releases -y
        - sudo add-apt-repository ppa:freecad-maintainers/freecad-stable -y
        - sudo apt-get update
        - sudo apt install gcc-7 g++-7
        - sudo apt install -y libocct-foundation-7.3 libocct-ocaf-7.3 libocct-data-exchange-7.3 libocct-foundation-dev libocct-ocaf-dev libocct-data-exchange-dev
 
        - git clone https://github.com/google/googletest googletest/
        - cd googletest
        - CXX=g++-7 CC=gcc-7 cmake .
        - make
        - sudo make install
        - cd ..

        - source ./tools/set_occt_paths.sh
        - CXX=g++-7 CC=gcc-7 cmake .
        - make

script:
  - echo "Ok"
