language: python

os: linux
python:
  "3.7"
      
install: 
  - echo "INSTALL"
  - pwd
  - ls

  - sudo apt install libocct-*
  - python3 -m pip install licant --user

  - python3 ./setup.py install --user

script:
  - echo "SCRIPT"
  - pwd
  - ls

