language: python

os: linux
python:
  "3.7"

apt:
  packages:
    - libocct-*
      
install: 
  - echo "INSTALL"
  - pwd
  - ls

  - python3 -m pip install licant

  - python3 ./setup.py install

script:
  - echo "SCRIPT"
  - pwd
  - ls

