language: python

os: linux
python:
  "3.7"
      
install: 
  - echo "INSTALL"
  - pwd
  - ls

  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:freecad-maintainers/occt-releases -y
  - sudo apt-get update
  - sudo apt install apt-file -y
  - sudo apt install libocct-foundation-7.3 -y
  - sudo apt install libocct-ocaf-7.3 -y
  - sudo apt install libocct-data-exchange-7.3 -y
  - sudo apt install libocct-foundation-dev -y
  - sudo apt install libocct-ocaf-dev -y
  - sudo apt install libocct-data-exchange-dev -y

  - cd /
  - sudo find . -name "gp_Pnt.hxx*"
  - cd -

  - ls /usr/include/opencascade || true
  - ls /usr/local/include/opencascade || true
  - ls /usr/include/ || true
  - ls /usr/include/x86_64-linux-gnu || true
  - ls /usr/local/include/ || true

  - locate libTKernel.so || true
  
  - python3 -m pip install licant
  - python3 ./setup.py install

script:
  - echo "SCRIPT"
  - pwd
  - ls

