language: python

matrix:
  include:

    - name: "OSX: Build by cmake"
      os: osx
      env: COMPILER=clang++ BUILD_TYPE=Release GSL_CXX_STANDARD=14
      osx_image: xcode11.2
      language: shell
      compiler: clang++

      script:
        - git clone https://github.com/mirmik/servoce-third-libs servoce-third-libs-travis
        - mkdir pyservoce/libs 
        - cp servoce-third-libs-travis/osx/* pyservoce/libs/

        - git clone https://github.com/pybind/pybind11
        
        - OCCT_INCLUDE="servoce-third-libs-travis/osx-include-7.4" cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON .
        - make VERBOSE=1


    - name: "OSX: Load from pypi"
      os: osx
      osx_image: xcode11.2
      language: shell

      install:
        - python3 -m pip install pyservoce

      script:
        - cd pytest
        - python3 ./inctest.py
        - python3 ./apitest.py

    - name: "OSX: Build by setup.py"
      os: osx
      osx_image: xcode11.2
      language: shell

      script:
        - git clone https://github.com/mirmik/servoce-third-libs servoce-third-libs-travis
        - mkdir pyservoce/libs 
        - cp servoce-third-libs-travis/osx-7.4/* pyservoce/libs/

        - git clone https://github.com/pybind/pybind11
        - python3 ./setup.py install

        - cd pytest
        - python3 ./inctest.py
        - python3 ./apitest.py


    - name: "Windows: Build by cmake"
      os : windows
      language : shell

      script:
        - git clone https://github.com/mirmik/servoce-third-libs servoce-third-libs-travis
        - mkdir pyservoce/libs 
        - cp servoce-third-libs-travis/win-7.4/* pyservoce/libs/
        - cp servoce-third-libs-travis/win-7.4/* pyservoce/
        - cp servoce-third-libs-travis/win-7.4/* servoce-third-libs-travis/win-lib-7.4/

        - git clone https://github.com/pybind/pybind11
        - export PATH="$TRAVIS_BUILD_DIR/servoce-third-libs-travis/win-7.4:$PATH"
        - export PATH="$TRAVIS_BUILD_DIR/servoce-third-libs-travis/win-lib-7.4:$PATH"

        - OCCT_INCLUDE="servoce-third-libs-travis/win-include-7.4" cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_GENERATOR_PLATFORM=x64 . 
        - cmake --build .


    - name: "Ubuntu: Build by cmake"
      os: linux
      python:
        "3.7"

      before_install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get -q update
        - sudo apt-get install libx11-dev mesa-common-dev libglu1-mesa-dev

      install: 
        - git clone https://github.com/mirmik/servoce-third-libs servoce-third-libs-travis
        - mkdir pyservoce/libs 
        - cp servoce-third-libs-travis/linux-7.4/* pyservoce/libs/

        - sudo apt install clang
        
        - git clone https://github.com/google/googletest googletest/
        - cd googletest
        - CXX=clang CC=clang cmake .
        - make
        - sudo make install
        - cd ..

        - source ./tools/set_occt_paths.sh
        - CXX=clang CC=clang cmake .
        - make


    - name: "Ubuntu: Load from pypi"
      os: linux
      python:
        "3.8"
            
      install: 
        - python3 -m pip install pyservoce

      script:
        - cd pytest
        - python3 ./inctest.py
        - python3 ./apitest.py


    - name: "Ubuntu: Build by setup.py"
      os: linux
      python:
        "3.7"

      before_install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get -q update
        - sudo apt-get install libx11-dev mesa-common-dev libglu1-mesa-dev
    
      install:       
        - git clone https://github.com/mirmik/servoce-third-libs servoce-third-libs-travis
        - mkdir pyservoce/libs 
        - cp servoce-third-libs-travis/linux-7.4/* pyservoce/libs/

        - git clone https://github.com/pybind/pybind11
        
        - python3 -m pip install licant
        - python3 ./setup.py install

      script:
        - cd pytest
        - python3 ./inctest.py
        - python3 ./apitest.py



script:
  - echo "Ok"
